# Vial/VIA
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

ENCODER_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = lite
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = no
CAPS_WORD_ENABLE = no
AUTO_SHIFT_ENABLE = no
POINTING_DEVICE_ENABLE = yes 
POINTING_DEVICE_AUTO_MOUSE_ENABLE = no 